PaulVeenemansPrijsApp/Areas/Admin/Controllers/ImportExcelController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;
using Mtk.Site.Mvc;
using Mtk.Site.Mvc.Pagination;
using Mtk.Site.Mvc.StatusMessage;
using Mtk.Site.Mvc.UI.Grid;
using Mtk.Site.Utility;
using Omu.ValueInjecter;
using PaulVeenemansPrijsDomain.BusinessLogic;
using PaulVeenemansPrijsDomain.Entities;
using PaulVeenemansPrijsDomain.Repositories;
using PaulVeenemansPrijsApp.Areas.Admin.Models;
using PaulVeenemansPrijsApp.SiteLogic;

namespace PaulVeenemansPrijsApp.Areas.Admin.Controllers
{
    [Authorize]
    public class ImportExcelController : MtkController
    {
        private readonly ImportExcelRepository _importExcelRepository;
        private readonly IParticipantRepository _participantRepository;
        private readonly ICalculationReportRepository _calculationReportRepository;

        public ImportExcelController(ImportExcelRepository importExcelRepository, IParticipantRepository participantRepository,
            ICalculationReportRepository calculationReportRepository)
        {
            _importExcelRepository = importExcelRepository;
            _participantRepository = participantRepository;
            _calculationReportRepository = calculationReportRepository;
        }

        //
        // GET: /ImportExcel/

        [HttpGet]
        public ViewResult Index(GridSortOptions sort, int? page)
        {
            const int pageSize = 20;
            ViewBag.sort = sort;
            IQueryable<ImportExcel> queryable = _importExcelRepository.All().Select(x => new ImportExcel
            {
                ImportExcelId = x.ImportExcelId,
                Race = x.Race,
                ChipNumberColumn = x.ChipNumberColumn,
                TeamNumberColumn = x.TeamNumberColumn,
                TimeColumn = x.TimeColumn,
                SkipRows = x.SkipRows,
                UploadDate = x.UploadDate,
                ImportDate = x.ImportDate,
                ExcelFileName = x.ExcelFileName
            });
            int count = queryable.Count();
            List<ImportExcel> pagedList = queryable.OrderBy(sort, m => m.ImportExcelId).Page(page, pageSize).ToList();
            var viewModel = new CustomPagination<ImportExcelViewModel>(pagedList.Select(ModelToViewModel), page ?? 1, pageSize, count);
            return View(viewModel);
        }

        //
        // GET: /ImportExcel/Details/5

        public ActionResult Details(int id)
        {
            ImportExcel importExcel = _importExcelRepository.FindBy(id);
            if (importExcel == null)
            {
                TempData.AddStatusWarning($"Excel-import met id {id} niet gevonden.");
                return RedirectToAction("Index");
            }

            return View(ModelToViewModel(importExcel));
        }

        //
        // GET: /ImportExcel/Create

        public ActionResult Create()
        {
            return View(new ImportExcelViewModel());
        }

        //
        // POST: /ImportExcel/Create

        [HttpPost]
        public ActionResult Create(ImportExcelViewModel viewModel, HttpPostedFileBase file)
        {
            if (!ModelState.IsValid)
            {
                return View(viewModel);
            }

            var importExcel = viewModel.MapToNew<ImportExcel>();
            importExcel.ChipNumberColumn = LetterToColumn(viewModel.ChipNumberLetter);
            importExcel.TeamNumberColumn = LetterToColumn(viewModel.TeamNumberLetter);
            importExcel.TimeColumn = LetterToColumn2(viewModel.TimeLetter);
            importExcel.UploadDate = DateTime.Now;
            if (file != null && file.ContentLength > 0 && Regex.IsMatch(file.ContentType, @"excel|spreadsheet", RegexOptions.IgnoreCase))
            {
                try
                {
                    importExcel.ExcelFileName = file.FileName;
                    importExcel.ExcelData = StreamToBytes(file.InputStream);
                    _importExcelRepository.Add(importExcel);
                    _importExcelRepository.Save();
                    TempData.AddStatusInfo($"Nieuwe Excel-import {importExcel.ImportExcelId} opgeslagen.");
                }
                catch (Exception e)
                {
                    TempData.AddStatusError($"Fout bij opslaan: {e.Message}.");
                }
            }
            else
            {
                return View(viewModel);
            }

            if (HttpContext.Request.IsAjaxRequest())
            {
                return PartialView("GridRow", ModelToViewModel(importExcel));
            }

            return RedirectToAction("Index");
        }

        //
        // GET: /ImportExcel/Edit/5

        public ActionResult Edit(int id)
        {
            ImportExcel importExcel = _importExcelRepository.FindBy(id);
            if (importExcel == null)
            {
                TempData.AddStatusWarning($"Excel-import met id {id} niet gevonden.");
                return RedirectToAction("Index");
            }

            ImportExcelViewModel viewModel = ModelToViewModel(importExcel);
            return View(viewModel);
        }

        //
        // POST or PUT: /ImportExcel/Edit/5

        [AcceptVerbs("POST", "PUT")]
        public ActionResult Edit(ImportExcelViewModel viewModel, HttpPostedFileBase file)
        {
            if (!ModelState.IsValid)
            {
                return View(viewModel);
            }

            ImportExcel importExcel = _importExcelRepository.FindBy(viewModel.ImportExcelId);
            importExcel.InjectFrom(viewModel);
            importExcel.ChipNumberColumn = LetterToColumn(viewModel.ChipNumberLetter);
            importExcel.TeamNumberColumn = LetterToColumn(viewModel.TeamNumberLetter);
            importExcel.TimeColumn = LetterToColumn2(viewModel.TimeLetter);
            if (file != null && file.ContentLength > 0 && Regex.IsMatch(file.ContentType, @"excel|spreadsheet", RegexOptions.IgnoreCase))
            {
                try
                {
                    importExcel.ExcelFileName = file.FileName;
                    importExcel.UploadDate = DateTime.Now;
                    importExcel.ImportDate = null;
                    importExcel.ExcelData = StreamToBytes(file.InputStream);
                    TempData.AddStatusInfo("File-data vervangen.");
                }
                catch (Exception e)
                {
                    TempData.AddStatusError($"Fout bij opslaan: {e.Message}.");
                }
            }

            _importExcelRepository.Update(importExcel);
            _importExcelRepository.Save();
            TempData.AddStatusInfo($"Excel-import {importExcel.ImportExcelId} gewijzigd.");
            if (HttpContext.Request.IsAjaxRequest())
            {
                return PartialView("GridRow", ModelToViewModel(importExcel));
            }

            return RedirectToAction("Index");
        }

        //
        // GET: /ImportExcel/Delete/5

        public ActionResult Delete(int id)
        {
            ImportExcel importExcel = _importExcelRepository.FindBy(id);
            if (importExcel == null)
            {
                TempData.AddStatusWarning($"Excel-import met id {id} niet gevonden.");
                return RedirectToAction("Index");
            }

            return View(ModelToViewModel(importExcel));
        }

        //
        // POST or DELETE: /ImportExcel/Delete/5

        [AcceptVerbs("POST", "DELETE"), ActionName("Delete")]
        public ActionResult DeletePost(int id)
        {
            try
            {
                ImportExcel importExcel = _importExcelRepository.FindBy(id);
                if (importExcel == null)
                {
                    return RedirectToAction("Index");
                }

                _importExcelRepository.Delete(importExcel);
                _importExcelRepository.Save();
                TempData.AddStatusInfo($"Excel-import {importExcel.ImportExcelId} verwijderd.");
            }
            catch (Exception e)
            {
                TempData.AddStatusError($"Kan Excel-import {id} niet verwijderen. {(e.InnerException != null ? e.InnerException.Message : e.Message)}");
            }

            return HttpContext.Request.IsAjaxRequest() ? TempData.MessageSummary() : RedirectToAction("Index");
        }

        public ActionResult Import(int id)
        {
            ImportExcel importExcel = _importExcelRepository.FindBy(id);
            try
            {
                int sheetsCount = importExcel.ExcelData.GetSheetsCount(GemBoxOptionsRetriever.GetLoadOptions(importExcel.ExcelFileName));
                if (sheetsCount > 1)
                {
                    TempData.AddStatusWarning($"Dit Excel-werkboek bevat {sheetsCount} werkbladen met gegevens. Alleen het eerste werkblad wordt verwerkt.");
                }

                importExcel.Import(_participantRepository);
                importExcel.ImportDate = DateTime.Now;
                _importExcelRepository.Update(importExcel);
                _importExcelRepository.Save();
                TempData.AddStatusInfo("Importactie voltooid.");
            }
            catch (Exception exception)
            {
                TempData.AddStatusError(string.Join(" *** ", Traverse(exception).Select(x => x.Message)));
            }

            return RedirectToAction("Index");
        }

        private static IEnumerable<Exception> Traverse(Exception root)
        {
            Exception temp = root;
            while (temp != null)
            {
                yield return temp;
                temp = temp.InnerException;
            }
        }

        public FileResult Download(int id)
        {
            ImportExcel importExcel = _importExcelRepository.FindBy(id);
            Response.AddHeader("Content-Disposition", $"attachment; filename=\"{importExcel.ExcelFileName}\"");

PaulVeenemansPrijsApp/Areas/Admin/Controllers/ViewExcelController.cs
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Text;
using System.Web.Mvc;
using System.Xml;
using GemBox.Spreadsheet;
using HtmlAgilityPack;
using Mtk.Site.Mvc;
using PaulVeenemansPrijsDomain.Entities;
using PaulVeenemansPrijsDomain.Repositories;
using PaulVeenemansPrijsApp.SiteLogic;

namespace PaulVeenemansPrijsApp.Areas.Admin.Controllers
{
    public class ViewExcelController : MtkController
    {
        private readonly ImportExcelRepository _importExcelRepository;

        public ViewExcelController(ImportExcelRepository importExcelRepository)
        {
            _importExcelRepository = importExcelRepository;
        }

        public ActionResult Index()
        {
            return RedirectToAction("Index", "ImportExcel");
        }

        public ActionResult View(int? id)
        {
            RemoveOldWorkDirectory();

            ImportExcel importExcel = _importExcelRepository.FindBy(id.GetValueOrDefault(0));
            if (importExcel == null)
            {
                return RedirectToAction("Index", "ImportExcel");
            }

            ViewBag.Id = id;
            ViewBag.Title = importExcel.ExcelFileName;
            ViewBag.LegendChipTeamText = importExcel.ChipNumberColumn != null ? "Chipnummer" : importExcel.TeamNumberColumn != null ? "Teamnummer" : "Onbekend";
            return View();
        }

        public ActionResult SheetContents(int? id)
        {
            ImportExcel importExcel = _importExcelRepository.FindBy(id.GetValueOrDefault(0));

            using (var memoryStream = new MemoryStream(importExcel.ExcelData))
            {
                string html = GetFirstSheetFromStreamAndReturnHtml(memoryStream,
                    GemBoxOptionsRetriever.GetLoadOptions(importExcel.ExcelFileName),
                    (importExcel.ChipNumberColumn ?? importExcel.TeamNumberColumn.GetValueOrDefault(1)) - 1,
                    importExcel.TimeColumn - 1,
                    importExcel.SkipRows);
                return Content(PostProcess(html), "text/html", Encoding.UTF8);
            }
        }

        private static string GetFirstSheetFromStreamAndReturnHtml(Stream stream, LoadOptions loadOptions, int markedColumn1, int markedColumn2, int skipRows)
        {
            ExcelFile book = ExcelFile.Load(stream, loadOptions);
            for (int i = book.Worksheets.Count - 1; i > 0; i--)
            {
                book.Worksheets.Remove(i);
            }

            try
            {
                ExcelWorksheet sheet = book.Worksheets[0];
                sheet.Columns[markedColumn1].Style.FillPattern.PatternStyle = FillPatternStyle.Solid;
                sheet.Columns[markedColumn1].Style.FillPattern.PatternForegroundColor = Color.FromArgb(255, 255, 0);
                sheet.Columns[markedColumn2].Style.FillPattern.PatternStyle = FillPatternStyle.Solid;
                sheet.Columns[markedColumn2].Style.FillPattern.PatternForegroundColor = Color.FromArgb(0, 205, 255);
                for (var r = 0; r < skipRows; r++)
                {
                    sheet.Rows[r].Style.FillPattern.PatternStyle = FillPatternStyle.Solid;
                    sheet.Rows[r].Style.FillPattern.PatternForegroundColor = Color.FromArgb(205, 102, 205);
                }

                book.Worksheets[0].SelectedRanges.Add(book.Worksheets[0], "A1");
                book.Worksheets[0].ViewOptions.FirstVisibleColumn = 0;
                book.Worksheets[0].ViewOptions.FirstVisibleRow = 0;
                book.Worksheets[0].SelectedRanges.Clear();
            }
            catch
            {
                // Skip.
            }

            using (var stringWriter = new StringWriter())
            {
                using (XmlWriter xmlWriter = XmlWriter.Create(stringWriter,
                    new XmlWriterSettings {Encoding = Encoding.UTF8, Indent = true, OmitXmlDeclaration = true}))
                {
                    HtmlSaveOptions saveOptions = SaveOptions.HtmlDefault;
                    saveOptions.Encoding = Encoding.UTF8;
                    saveOptions.HtmlType = HtmlType.Html;
                    saveOptions.WriteCellAddress = true;
                    book.Save(xmlWriter, saveOptions);
                }

                return stringWriter.ToString();
            }
        }

        private static string PostProcess(string html)
        {
            var doc = new HtmlDocument();
            doc.LoadHtml(html);

            AddStyle();

            HtmlNode table = doc.DocumentNode.SelectSingleNode("//table");
            if (table == null)
            {
                return html;
            }

            AddRowNumbers(table);
            AddColumnLetters(table);

            using (var stringWriter = new StringWriter())
            {
                doc.Save(stringWriter);
                return stringWriter.ToString();
            }

            void AddStyle()
            {
                HtmlNode head = doc.DocumentNode.SelectSingleNode("//head");
                head.AppendChild(HtmlNode.CreateNode(string.Join(" ",
                    "<style>",
                    "td, th { border: 1px solid #d0d0d0; }",
                    ".excel-head { background-color: #e8e8e8; font-weight: 400; text-align: center; }",
                    "</style>")));
            }

            void AddRowNumbers(HtmlNode t)
            {
                t.PrependChild(HtmlNode.CreateNode("<col style=\"width: 36px;\">"));

                var r = 0;
                foreach (HtmlNode row in t.SelectNodes("//tr"))
                {
                    row.PrependChild(HtmlNode.CreateNode($"<td class=\"excel-head\">{++r}</td>"));
                }
            }

            void AddColumnLetters(HtmlNode t)
            {
                HtmlNode headerRow = HtmlNode.CreateNode("<tr><th class=\"excel-head\"></th></tr>");

                for (var c = 0; c < t.SelectNodes("//col").Sum(x => x.GetAttributeValue("span", 1)) - 1; c++)
                {
                    var columnLetter = new string(IntToLetters(c).Reverse().ToArray());
                    headerRow.AppendChild(HtmlNode.CreateNode($"<th class=\"excel-head\">{columnLetter}</th>"));
                }

                t.InsertBefore(headerRow, t.SelectSingleNode("//tr"));
            }
        }

        private void RemoveOldWorkDirectory()
        {
            string directory = Server.MapPath("~/App_Data/WorkDirectory");
            try
            {
                if (Directory.Exists(directory))
                {
                    Directory.Delete(directory, true);
                }
            }
            catch
            {
                // Skip.
            }
        }

        private static IEnumerable<char> IntToLetters(int number)
        {
            while (number >= 0)
            {
                yield return (char)(65 + number % 26);
                number = number / 26 - 1;
            }
        }
    }
}

PaulVeenemansPrijsApp/Areas/Admin/Views/ImportExcel/Create.cshtml
@model ImportExcelViewModel

@{
    ViewBag.Title = "Nieuwe Excel-import";
    ViewBag.Action = "Create";
}

@Html.Partial("_CreateOrEdit", Model)

PaulVeenemansPrijsApp/Areas/Admin/Views/ImportExcel/Delete.cshtml
@model ImportExcelViewModel

@{
    ViewBag.Title = "Excel-import verwijderen";
}

<h2>@ViewBag.Title</h2>

@Html.GetMessageSummary()

<h3>Weet je zeker dat je de volgende Excel-import wilt verwijderen?</h3>
<fieldset>
    <legend style="display: none;"></legend>
    <div>
        <div class="display-label">
            @Html.LabelFor(model => model.Race)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.Race)
        </div>
    </div>
    <div>
        <div class="display-label">
            @Html.LabelFor(model => model.ChipNumberLetter)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.ChipNumberLetter)
        </div>
    </div>
    <div>
        <div class="display-label">
            @Html.LabelFor(model => model.TeamNumberLetter)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.TeamNumberLetter)
        </div>
    </div>
    <div>
        <div class="display-label">
            @Html.LabelFor(model => model.TimeLetter)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.TimeLetter)
        </div>
    </div>
    <div>
        <div class="display-label">
            @Html.LabelFor(model => model.SkipRows)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.SkipRows)
        </div>
    </div>
    <div>
        <div class="display-label">
            @Html.LabelFor(model => model.UploadDate)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.UploadDate)
        </div>
    </div>
    <div>
        <div class="display-label">
            @Html.LabelFor(model => model.ImportDate)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.ImportDate)
        </div>
    </div>
    <div>
        <div class="display-label">
            @Html.LabelFor(model => model.ExcelFileName)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.ExcelFileName)
        </div>
    </div>
</fieldset>
@using (Html.BeginForm(new {id = Model.ImportExcelId}))
{
    <p>
        @Html.HiddenFor(model => model.ImportExcelId)
        <input type="submit" value="Verwijderen" /> |
        @Html.MtkActionLink("Terug naar overzicht", "Index")
    </p>
}

PaulVeenemansPrijsApp/Areas/Admin/Views/ImportExcel/Details.cshtml
@model ImportExcelViewModel

@{
    ViewBag.Title = "Excel-import";
}

<h2>@ViewBag.Title</h2>

<fieldset>
    <legend style="display: none;"></legend>
    <div>
        <div class="display-label">
            @Html.LabelFor(model => model.Race)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.Race)
        </div>
    </div>
    <div>
        <div class="display-label">
            @Html.LabelFor(model => model.ChipNumberLetter)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.ChipNumberLetter)
        </div>
    </div>
    <div>
        <div class="display-label">
            @Html.LabelFor(model => model.TeamNumberLetter)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.TeamNumberLetter)
        </div>
    </div>
    <div>
        <div class="display-label">
            @Html.LabelFor(model => model.TimeLetter)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.TimeLetter)
        </div>
    </div>
    <div>
        <div class="display-label">
            @Html.LabelFor(model => model.SkipRows)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.SkipRows)
        </div>
    </div>
    <div>
        <div class="display-label">
            @Html.LabelFor(model => model.UploadDate)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.UploadDate)
        </div>
    </div>
    <div>
        <div class="display-label">
            @Html.LabelFor(model => model.ImportDate)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.ImportDate)
        </div>
    </div>
    <div>
        <div class="display-label">
            @Html.LabelFor(model => model.ExcelFileName)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.ExcelFileName)
        </div>
    </div>
</fieldset>
<p>
    @Html.MtkActionLink("Bewerken", "Edit", new {id = Model.ImportExcelId}) |
    @Html.MtkActionLink("Terug naar overzicht", "Index")
</p>

PaulVeenemansPrijsApp/Areas/Admin/Views/ImportExcel/Edit.cshtml
@model ImportExcelViewModel

@{
    ViewBag.Title = "Excel-import bewerken";
    ViewBag.Action = "Edit";
}

@Html.Partial("_CreateOrEdit", Model)

PaulVeenemansPrijsApp/Areas/Admin/Views/ImportExcel/GridRow.cshtml
@model ImportExcelViewModel

<div>
    @Html.GetMessageSummary()
    @Html.SingleGridRow(Model).Columns(column =>
    {
        column.For(m => m.ImportExcelId).Attributes(style => "width: 32px; overflow: hidden;").HeaderAttributes(style => "width: 32px; overflow: hidden;");
        column.For(m => m.Race).Attributes(style => "width: 66px;").HeaderAttributes(style => "width: 66px; overflow: hidden;");
        column.For(m => m.ChipNumberLetter).Attributes(style => "width: 53px;").HeaderAttributes(style => "width: 53px; overflow: hidden;");
        column.For(m => m.TeamNumberLetter).Attributes(style => "width: 53px;").HeaderAttributes(style => "width: 53px; overflow: hidden;");
        column.For(m => m.TimeLetter).Attributes(style => "width: 53px;").HeaderAttributes(style => "width: 53px; overflow: hidden;");
        column.For(m => m.SkipRows).Attributes(style => "width: 53px;").HeaderAttributes(style => "width: 53px; overflow: hidden;");
        column.For(m => m.UploadDate).Attributes(style => "width: 72px;").HeaderAttributes(style => "width: 72px; overflow: hidden;");
        column.For(m => m.ImportDate).Attributes(style => "width: 72px;").HeaderAttributes(style => "width: 72px; overflow: hidden;");
        column.Custom(m => Html.ActionLink(m.ExcelFileName, "View", "ViewExcel", new {id = m.ImportExcelId}, null)).Sortable(true).SortColumnName("ExcelFileName").Attributes(style => "width: 247px; overflow: hidden;").HeaderAttributes(style => "width: 247px; overflow: hidden;");
        column.Custom(m => Html.MakeGridLinksFor(new {id = m.ImportExcelId}) + " " + Html.ActionLink("Importeren", "Import", new {id = m.ImportExcelId}, new {@class = "Import database_go.png"}) + " " + Html.ActionLink("Downloaden", "Download", new {id = m.ImportExcelId}, new {@class = "Download export_excel.png"})).Sortable(false).Attributes(style => "width: 108px; overflow: hidden;").HeaderAttributes(style => "width: 108px; overflow: hidden;");
    })
</div>

PaulVeenemansPrijsApp/Areas/Admin/Views/ImportExcel/Index.cshtml
@using PaulVeenemansPrijsDomain.BusinessLogic
@model IEnumerable<ImportExcelViewModel>

@{
    ViewBag.Title = "Uitslagen verwerken";
}
<div class="new-entity-link">
    @Html.MtkActionLink("Nieuwe Excel-import", "Create", null, new {@class = "Create add24px.png"})
</div>

<h2>@ViewBag.Title</h2>
<em>Excel-imports van uitslagen per onderdeel</em>

@Html.GetMessageSummary()

@Html.MtkGridPager(Model)

@Html.Grid(Model).Columns(column =>
{
    column.For(m => m.ImportExcelId).Attributes(style => "width: 32px; overflow: hidden;").HeaderAttributes(style => "width: 32px; overflow: hidden;");
    column.For(m => m.Race).Attributes(style => "width: 66px;").HeaderAttributes(style => "width: 66px; overflow: hidden;");
    column.For(m => m.ChipNumberLetter).Attributes(style => "width: 53px;").HeaderAttributes(style => "width: 53px; overflow: hidden;");
    column.For(m => m.TeamNumberLetter).Attributes(style => "width: 53px;").HeaderAttributes(style => "width: 53px; overflow: hidden;");
    column.For(m => m.TimeLetter).Attributes(style => "width: 53px;").HeaderAttributes(style => "width: 53px; overflow: hidden;");
    column.For(m => m.SkipRows).Attributes(style => "width: 53px;").HeaderAttributes(style => "width: 53px; overflow: hidden;");
    column.For(m => m.UploadDate).Attributes(style => "width: 72px;").HeaderAttributes(style => "width: 72px; overflow: hidden;");
    column.For(m => m.ImportDate).Attributes(style => "width: 72px;").HeaderAttributes(style => "width: 72px; overflow: hidden;");
    column.Custom(m => Html.ActionLink(m.ExcelFileName, "View", "ViewExcel", new {id = m.ImportExcelId}, null)).Sortable(true).SortColumnName("ExcelFileName").Attributes(style => "width: 247px; overflow: hidden;").HeaderAttributes(style => "width: 247px; overflow: hidden;");
    column.Custom(m => Html.MakeGridLinksFor(new {id = m.ImportExcelId}) + " " + Html.ActionLink("Importeren", "Import", new {id = m.ImportExcelId}, new {@class = "Import database_go.png"}) + " " + Html.ActionLink("Downloaden", "Download", new {id = m.ImportExcelId}, new {@class = "Download export_excel.png"})).Sortable(false).Attributes(style => "width: 108px; overflow: hidden;").HeaderAttributes(style => "width: 108px; overflow: hidden;");
}).Attributes(@class => "grid-editing", style => "width: 920px; table-layout: fixed;").Sort(ViewBag.sort)

<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<div>
    <fieldset style="float: left;">
        <legend>Scorekolom helemaal leegmaken (LET OP)</legend>
        <em>Terugzetten van de tijden is mogelijk door het desbetreffende Excelsheet (of meerdere sheets) opnieuw te importeren</em>
        <div style="clear: both;"></div>
        @using (Html.BeginForm("ClearColumn", "ImportExcel", null, FormMethod.Post, new {style = "display:block;float:left;margin-right:12px;"}))
        {
            <p>
                @Html.Hidden("id", Parts.Cycling)
                <input onclick="return confirm('Wielrennen leegmaken -- Weet je het zeker!?')" style="width: 210px;" type="submit" value="Wielrennen leegmaken"/>
            </p>
        }
        @using (Html.BeginForm("ClearColumn", "ImportExcel", null, FormMethod.Post, new {style = "display:block;float:left;margin-right:12px;"}))
        {
            <p>
                @Html.Hidden("id", Parts.Skating)
                <input onclick="return confirm('Schaatsen leegmaken -- Weet je het zeker!?')" style="width: 210px;" type="submit" value="Schaatsen leegmaken"/>
            </p>
        }
        @using (Html.BeginForm("ClearColumn", "ImportExcel", null, FormMethod.Post, new {style = "display:block;float:left;margin-right:12px;"}))
        {
            <p>
                @Html.Hidden("id", Parts.Running)
                <input onclick="return confirm('Hardlopen leegmaken -- Weet je het zeker!?')" style="width: 210px;" type="submit" value="Hardlopen leegmaken"/>
            </p>
        }
        @using (Html.BeginForm("ClearColumn", "ImportExcel", null, FormMethod.Post, new {style = "display:block;float:left;"}))
        {
            <p>
                @Html.Hidden("id", Parts.Rowing)
                <input onclick="return confirm('Roeien leegmaken -- Weet je het zeker!?')" style="width: 210px;" type="submit" value="Roeien leegmaken"/>
            </p>
        }
        <div style="clear: both;"></div>
    </fieldset>
</div>
<div style="clear: both;"></div>