PaulVeenemansPrijsApp/Areas/Admin/Models/ParticipantViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace PaulVeenemansPrijsApp.Areas.Admin.Models
{
    public class ParticipantViewModel
    {
        public int Index { get; set; }

        [Display(Name = "Id"), Key]
        public int ParticipantId { get; set; }

        [Display(Name = "Teamvolgnummer"), Required]
        public int TeamSeqNumber { get; set; }

        [Display(Name = "Chipnummer"), StringLength(50), Required]
        public string ChipNumber { get; set; }

        [Display(Name = "Racecode groot"), StringLength(50), Required]
        public string RaceCodeMajor { get; set; }

        [Display(Name = "Racecode klein"), StringLength(10)]
        public string RaceCodeMinor { get; set; }

        [Display(Name = "Teamcode"), StringLength(50), Required]
        public string TeamCode { get; set; }

        [Display(Name = "Naam deelnemer"), StringLength(100), Required]
        public string ParticipantName { get; set; }

        [Display(Name = "Code roeien"), RegularExpression(@"^(?:[12]x|2-)$", ErrorMessage = "Kies 1x, 2x of 2-.")]
        public string CodeRowing { get; set; }

        [Display(Name = "Schaatsen tijd"), RegularExpression(@"^(?!00:00)\d\d:\d\d(?:\.\d+)?$", ErrorMessage = "Tijd als MM:SS.00 of leeg")]
        public string SkatingTime { get; set; }

        [Display(Name = "Schaatsen straf"), RegularExpression(@"^(?!00:00)\d\d:\d\d(?:\.\d+)?$", ErrorMessage = "Tijd als MM:SS.00 of leeg")]
        public string SkatingPenalty { get; set; }

        [Display(Name = "Schaatsen status")]
        public int SkatingStatusStatusId { get; set; }

        [Display(Name = "Schaatsen status")]
        public string SkatingStatusCode { get; set; }

        [Display(Name = "Schaatsen status")]
        public string SkatingStatusDescription { get; set; }

        [Display(Name = "Schaatsen score"), DisplayFormat(DataFormatString = "{0:n1}")]
        public double SkatingScore { get; set; }

        [Display(Name = "Hardlopen tijd"), RegularExpression(@"^(?!00:00)\d\d:\d\d(?:\.\d+)?$", ErrorMessage = "Tijd als MM:SS.00 of leeg")]
        public string RunningTime { get; set; }

        [Display(Name = "Hardlopen straf"), RegularExpression(@"^(?!00:00)\d\d:\d\d(?:\.\d+)?$", ErrorMessage = "Tijd als MM:SS.00 of leeg")]
        public string RunningPenalty { get; set; }

        [Display(Name = "Hardlopen status")]
        public int RunningStatusStatusId { get; set; }

        [Display(Name = "Hardlopen status")]
        public string RunningStatusCode { get; set; }

        [Display(Name = "Hardlopen status")]
        public string RunningStatusDescription { get; set; }

        [Display(Name = "Hardlopen score"), DisplayFormat(DataFormatString = "{0:n1}")]
        public double RunningScore { get; set; }

        [Display(Name = "Wielrennen tijd"), RegularExpression(@"^(?!00:00)\d\d:\d\d(?:\.\d+)?$", ErrorMessage = "Tijd als MM:SS.00 of leeg")]
        public string CyclingTime { get; set; }

        [Display(Name = "Wielrennen straf"), RegularExpression(@"^(?!00:00)\d\d:\d\d(?:\.\d+)?$", ErrorMessage = "Tijd als MM:SS.00 of leeg")]
        public string CyclingPenalty { get; set; }

        [Display(Name = "Wielrennen status")]
        public int CyclingStatusStatusId { get; set; }

        [Display(Name = "Wielrennen status")]
        public string CyclingStatusCode { get; set; }

        [Display(Name = "Wielrennen status")]
        public string CyclingStatusDescription { get; set; }

        [Display(Name = "Wielrennen score"), DisplayFormat(DataFormatString = "{0:n1}")]
        public double CyclingScore { get; set; }

        [Display(Name = "Roeien tijd"), RegularExpression(@"^(?!00:00)\d\d:\d\d(?:\.\d+)?$", ErrorMessage = "Tijd als MM:SS.00 of leeg")]
        public string RowingTime { get; set; }

        [Display(Name = "Roeien straf"), RegularExpression(@"^(?!00:00)\d\d:\d\d(?:\.\d+)?$", ErrorMessage = "Tijd als MM:SS.00 of leeg")]
        public string RowingPenalty { get; set; }

        [Display(Name = "Roeien gecorrigeerd"), RegularExpression(@"^(?!00:00)\d\d:\d\d(?:\.\d+)?$", ErrorMessage = "Tijd als MM:SS.00 of leeg")]
        public string RowingTimeCorrected { get; set; }

        [Display(Name = "Roeien status")]
        public int RowingStatusStatusId { get; set; }

        [Display(Name = "Roeien status")]
        public string RowingStatusCode { get; set; }

        [Display(Name = "Roeien status")]
        public string RowingStatusDescription { get; set; }

        [Display(Name = "Roeien score"), DisplayFormat(DataFormatString = "{0:n1}")]
        public double RowingScore { get; set; }

        [Display(Name = "Totaalscore"), DisplayFormat(DataFormatString = "{0:n3}")]
        public double OverallScore { get; set; }

        [Display(Name = "Volgnr groot")]
        public int? RankMajor { get; set; }

        [Display(Name = "Volgnr klein")]
        public int? RankMinor { get; set; }

        [Display(Name = "Racegroep")]
        public int RaceGroupRaceGroupId { get; set; }

        [Display(Name = "Racegroep")]
        public string RaceGroupRaceGroupDescription { get; set; }

        public IEnumerable<SelectListItem> RaceGroups { get; set; }
        public IEnumerable<SelectListItem> Statuses { get; set; }
    }
}

PaulVeenemansPrijsApp/Areas/Admin/Controllers/ParticipantController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;
using Mtk.Site.Mvc;
using Mtk.Site.Mvc.Pagination;
using Mtk.Site.Mvc.StatusMessage;
using Mtk.Site.Mvc.UI.Grid;
using Mtk.Site.Utility;
using Omu.ValueInjecter;
using PaulVeenemansPrijsDomain.Entities;
using PaulVeenemansPrijsDomain.Repositories;
using PaulVeenemansPrijsApp.Areas.Admin.Models;
using PaulVeenemansPrijsApp.SiteLogic;

namespace PaulVeenemansPrijsApp.Areas.Admin.Controllers
{
    [Authorize]
    public class ParticipantController : MtkController
    {
        private readonly IParticipantExcelRepository _participantExcelRepository;
        private readonly IParticipantRepository _participantRepository;
        private readonly IRaceGroupRepository _raceGroupRepository;
        private readonly IStatusRepository _statusRepository;

        public ParticipantController(IParticipantRepository repository, IRaceGroupRepository raceGroupRepository, IStatusRepository statusRepository,
            IParticipantExcelRepository participantExcelRepository)
        {
            _participantRepository = repository;
            _raceGroupRepository = raceGroupRepository;
            _statusRepository = statusRepository;
            _participantExcelRepository = participantExcelRepository;
        }

        //
        // GET: /Participant/

        [HttpGet]
        public ViewResult Index(GridSortOptions sort, int? page, string filter)
        {
            const int pageSize = 20;
            ViewBag.sort = sort;
            ViewBag.filter = filter;
            int numericFilter = !string.IsNullOrEmpty(filter) && Regex.IsMatch(filter, @"^\d+$") ? int.Parse(filter) : 0;
            IQueryable<Participant> queryable =
                _participantRepository.FilterBy(
                    x =>
                    string.IsNullOrEmpty(filter) || x.ChipNumber.Contains(filter) || x.ParticipantName.Contains(filter) || x.TeamSeqNumber == numericFilter
                    || x.TeamCode.Contains(filter));
            int count = queryable.Count();
            List<Participant> pagedList = queryable.OrderBy(sort, m => m.ParticipantId).Page(page, pageSize).ToList();
            var viewModel = new CustomPagination<ParticipantViewModel>(pagedList.Select(m => m.MapToNewParticipantViewModel()), page ?? 1, pageSize, count);
            return View(viewModel);
        }

        //
        // GET: /Participant/Details/5

        public ActionResult Details(int id)
        {
            Participant participant = _participantRepository.FindBy(id);
            if (participant == null)
            {
                TempData.AddStatusWarning($"Deelnemer met id {id} niet gevonden.");
                return RedirectToAction("Index");
            }

            return View(participant.MapToNewParticipantViewModel());
        }

        //
        // GET: /Participant/Create

        public ActionResult Create()
        {
            return View(new ParticipantViewModel {RaceGroups = RaceGroupSelectList(0), Statuses = StatusSelectList()});
        }

        //
        // POST or PUT: /Participant/Create

        [HttpPost]
        public ActionResult Create(ParticipantViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                viewModel.RaceGroups = RaceGroupSelectList(viewModel.RaceGroupRaceGroupId);
                viewModel.Statuses = StatusSelectList();
                return View(viewModel);
            }

            var participant = new Participant {Skating = new Part(), Running = new Part(), Cycling = new Part(), Rowing = new RowingPart()};
            MapParticipantViewModelToParticipant(viewModel, participant);
            _participantRepository.Add(participant);
            _participantRepository.Save();
            TempData.AddStatusInfo($"Nieuwe deelnemer {participant.ParticipantId} opgeslagen.");
            if (HttpContext.Request.IsAjaxRequest())
            {
                return PartialView("GridRow", participant.MapToNewParticipantViewModel());
            }

            return RedirectToAction("Index");
        }

        //
        // GET: /Participant/Edit/5

        public ActionResult Edit(int id)
        {
            Participant participant = _participantRepository.FindBy(id);
            if (participant == null)
            {
                TempData.AddStatusWarning($"Deelnemer met id {id} niet gevonden.");
                return RedirectToAction("Index");
            }

            ParticipantViewModel viewModel = participant.MapToNewParticipantViewModel();
            viewModel.RaceGroups = RaceGroupSelectList(viewModel.RaceGroupRaceGroupId);
            viewModel.Statuses = StatusSelectList();
            return View(viewModel);
        }

        //
        // POST or PUT: /Participant/Edit/5

        [AcceptVerbs("POST", "PUT")]
        public ActionResult Edit(ParticipantViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                viewModel.RaceGroups = RaceGroupSelectList(viewModel.RaceGroupRaceGroupId);
                viewModel.Statuses = StatusSelectList();
                return View(viewModel);
            }

            Participant participant = _participantRepository.FindBy(viewModel.ParticipantId);
            MapParticipantViewModelToParticipant(viewModel, participant);
            _participantRepository.Update(participant);
            _participantRepository.Save();
            TempData.AddStatusInfo($"Deelnemer {participant.ParticipantId} gewijzigd.");
            if (HttpContext.Request.IsAjaxRequest())
            {
                return PartialView("GridRow", participant.MapToNewParticipantViewModel());
            }

            return RedirectToAction("Index");
        }

        //
        // GET: /Participant/Delete/5

        public ActionResult Delete(int id)
        {
            Participant participant = _participantRepository.FindBy(id);
            if (participant == null)
            {
                TempData.AddStatusWarning($"Deelnemer met id {id} niet gevonden.");
                return RedirectToAction("Index");
            }

            return View(participant.MapToNewParticipantViewModel());
        }

        //
        // POST or DELETE: /Participant/Delete/5

        [AcceptVerbs("POST", "DELETE"), ActionName("Delete")]
        public ActionResult DeletePost(int id)
        {
            try
            {
                Participant participant = _participantRepository.FindBy(id);
                if (participant == null)
                {
                    return RedirectToAction("Index");
                }

                _participantRepository.Delete(participant);
                _participantRepository.Save();
                TempData.AddStatusInfo($"Deelnemer {participant.ParticipantId} verwijderd.");
            }
            catch (Exception e)
            {
                TempData.AddStatusError($"Kan deelnemer {id} niet verwijderen. {(e.InnerException != null ? e.InnerException.Message : e.Message)}");
            }

            return HttpContext.Request.IsAjaxRequest() ? TempData.MessageSummary() : RedirectToAction("Index");
        }

        public ActionResult Import()
        {
            return View();
        }

        [HttpPost, ActionName("Import")]
        public ActionResult ImportConfirmed(HttpPostedFileBase file)
        {
            if (file == null || file.ContentLength <= 0 || !Regex.IsMatch(file.ContentType, @"excel|spreadsheet", RegexOptions.IgnoreCase))
            {
                ModelState.AddModelError("", "File must be an Excel document.");
                return View();
            }

            IQueryable<Participant> participants = _participantRepository.All();
            if (participants.Any())
            {
                foreach (Participant participant in participants)
                {
                    _participantRepository.Delete(participant);
                }

                TempData.AddStatusInfo("Oude deelnemers verwijderd.");
            }

            byte[] data;
            using (var ms = new MemoryStream())
            {
                file.InputStream.CopyTo(ms);
                data = ms.GetBuffer();
            }

            try
            {
                _participantExcelRepository.Add(new ParticipantExcel {ExcelFileName = file.FileName, ExcelData = data});
                _participantExcelRepository.Save();
            }
            catch (Exception e)
            {
                TempData.AddStatusWarning($"Excel document could not be saved in the database. {e.Message}");
            }

            var loadOptions = GemBoxOptionsRetriever.GetLoadOptions(file.FileName);
            try
            {
                int sheetsCount = data.GetSheetsCount(loadOptions);
                if (sheetsCount > 1)
                {
                    TempData.AddStatusWarning($"Dit Excel-werkboek bevat {sheetsCount} werkbladen met gegevens. Alleen het eerste werkblad wordt verwerkt.");
                }

                data.Import(loadOptions, _participantRepository, _raceGroupRepository, _statusRepository);
            }
            catch (Exception e)
            {
                TempData.AddStatusError($"Importfout. {e.Message}");
                return RedirectToAction("Index");
            }

            TempData.AddStatusInfo("Nieuwe deelnemers geïmporteerd.");
            return RedirectToAction("Index");
        }

        public ActionResult Download()
        {
            ParticipantExcel participantExcel = _participantExcelRepository.All().OrderByDescending(x => x.ParticipantExcelId).FirstOrDefault();
            if (participantExcel != null)
            {
                return File(participantExcel.ExcelData, "application/vnd.excel", participantExcel.ExcelFileName);
            }

PaulVeenemansPrijsApp/Areas/Admin/Views/Participant/Create.cshtml
@model ParticipantViewModel

@{
    ViewBag.Title = "Nieuwe deelnemer";
    ViewBag.Action = "Create";
}

@Html.Partial("_CreateOrEdit", Model)

PaulVeenemansPrijsApp/Areas/Admin/Views/Participant/Delete.cshtml
@model ParticipantViewModel

@{
    ViewBag.Title = "Deelnemer verwijderen";
}

<h2>@ViewBag.Title</h2>

@Html.GetMessageSummary()

<h3>Weet je zeker dat je de volgende deelnemer wilt verwijderen?</h3>
<fieldset>
    <legend style="display: none;"></legend>
    <div>
        <div class="display-label">
            @Html.LabelFor(model => model.ChipNumber)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.ChipNumber)
        </div>
    </div>
    <div>
        <div class="display-label">
            @Html.LabelFor(model => model.RaceCodeMajor)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.RaceCodeMajor)
        </div>
    </div>
    <div>
        <div class="display-label">
            @Html.LabelFor(model => model.RaceCodeMinor)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.RaceCodeMinor)
        </div>
    </div>
    <div>
        <div class="display-label">
            @Html.LabelFor(model => model.TeamCode)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.TeamCode)
        </div>
    </div>
    <div>
        <div class="display-label">
            @Html.LabelFor(model => model.ParticipantName)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.ParticipantName)
        </div>
    </div>
    <div>
        <div class="display-label">
            @Html.LabelFor(model => model.CodeRowing)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.CodeRowing)
        </div>
    </div>
    <div>
        <div class="display-label">
            @Html.LabelFor(model => model.RaceGroupRaceGroupDescription)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.RaceGroupRaceGroupDescription)
        </div>
    </div>
    <div>
        <div class="display-label">
            @Html.LabelFor(model => model.OverallScore)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.OverallScore)
        </div>
    </div>
</fieldset>
@using (Html.BeginForm(new {id = Model.ParticipantId}))
{
    <p>
        @Html.HiddenFor(model => model.ParticipantId)
        <input type="submit" value="Verwijderen" /> |
        @Html.MtkActionLink("Terug naar overzicht", "Index")
    </p>
}

PaulVeenemansPrijsApp/Areas/Admin/Views/Participant/Details.cshtml
@model ParticipantViewModel

@{
    ViewBag.Title = "Deelnemer";
}

<h2>@ViewBag.Title</h2>

<fieldset style="float: left; margin-right: 12px;">
    <legend style="display: none;"></legend>
    <div>
        <div class="display-label">
            @Html.LabelFor(model => model.TeamSeqNumber)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.TeamSeqNumber)
        </div>
    </div>
    <div>
        <div class="display-label">
            @Html.LabelFor(model => model.ChipNumber)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.ChipNumber)
        </div>
    </div>
    <div>
        <div class="display-label">
            @Html.LabelFor(model => model.RaceCodeMajor)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.RaceCodeMajor)
        </div>
    </div>
    <div>
        <div class="display-label">
            @Html.LabelFor(model => model.RaceCodeMinor)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.RaceCodeMinor)
        </div>
    </div>
    <div>
        <div class="display-label">
            @Html.LabelFor(model => model.TeamCode)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.TeamCode)
        </div>
    </div>
    <div>
        <div class="display-label">
            @Html.LabelFor(model => model.ParticipantName)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.ParticipantName)
        </div>
    </div>
    <div>
        <div class="display-label">
            @Html.LabelFor(model => model.CodeRowing)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.CodeRowing)
        </div>
    </div>
    <div>
        <div class="display-label">
            @Html.LabelFor(model => model.RaceGroupRaceGroupDescription)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.RaceGroupRaceGroupDescription)
        </div>
    </div>
    <div>
        <div class="display-label">
            @Html.LabelFor(model => model.RankMajor)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.RankMajor)
        </div>
    </div>
    <div>
        <div class="display-label">
            @Html.LabelFor(model => model.RankMinor)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.RankMinor)
        </div>
    </div>
    <div>
        <div class="display-label">
            @Html.LabelFor(model => model.OverallScore)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.OverallScore)
        </div>
    </div>
</fieldset>
<fieldset style="float: right;">
    <legend style="display: none;"></legend>
    <div>
        <div class="display-label">
            @Html.LabelFor(model => model.SkatingTime)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.SkatingTime)
        </div>
    </div>
    <div>
        <div class="display-label">
            @Html.LabelFor(model => model.SkatingPenalty)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.SkatingPenalty)
        </div>
    </div>
    <div>
        <div class="display-label">
            @Html.LabelFor(model => model.SkatingStatusDescription)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.SkatingStatusDescription)
        </div>
    </div>
    <div>
        <div class="display-label">
            @Html.LabelFor(model => model.SkatingScore)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.SkatingScore)
        </div>
    </div>
    <div>
        <div class="display-label">
            @Html.LabelFor(model => model.RunningTime)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.RunningTime)
        </div>
    </div>
    <div>
        <div class="display-label">
            @Html.LabelFor(model => model.RunningPenalty)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.RunningPenalty)
        </div>
    </div>
    <div>
        <div class="display-label">
            @Html.LabelFor(model => model.RunningStatusDescription)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.RunningStatusDescription)
        </div>
    </div>
    <div>
        <div class="display-label">
            @Html.LabelFor(model => model.RunningScore)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.RunningScore)
        </div>
    </div>
    <div>
        <div class="display-label">
            @Html.LabelFor(model => model.CyclingTime)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.CyclingTime)
        </div>
    </div>
    <div>
        <div class="display-label">
            @Html.LabelFor(model => model.CyclingPenalty)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.CyclingPenalty)
        </div>
    </div>
    <div>
        <div class="display-label">
            @Html.LabelFor(model => model.CyclingStatusDescription)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.CyclingStatusDescription)
        </div>
    </div>
    <div>
        <div class="display-label">
            @Html.LabelFor(model => model.CyclingScore)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.CyclingScore)
        </div>
    </div>
    <div>
        <div class="display-label">
            @Html.LabelFor(model => model.RowingTime)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.RowingTime)
        </div>
    </div>
    <div>
        <div class="display-label">
            @Html.LabelFor(model => model.RowingPenalty)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.RowingPenalty)
        </div>
    </div>
    <div>
        <div class="display-label">
            @Html.LabelFor(model => model.RowingTimeCorrected)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.RowingTimeCorrected)
        </div>
    </div>
    <div>
        <div class="display-label">
            @Html.LabelFor(model => model.RowingStatusDescription)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.RowingStatusDescription)
        </div>
    </div>
    <div>
        <div class="display-label">
            @Html.LabelFor(model => model.RowingScore)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.RowingScore)
        </div>
    </div>
</fieldset>
<p>
    @Html.MtkActionLink("Bewerken", "Edit", new {id = Model.ParticipantId}) |
    @Html.MtkActionLink("Terug naar overzicht", "Index")
</p>

PaulVeenemansPrijsApp/Areas/Admin/Views/Participant/Edit.cshtml
@model ParticipantViewModel

@{
    ViewBag.Title = "Deelnemer bewerken";
    ViewBag.Action = "Edit";
}

@Html.Partial("_CreateOrEdit", Model)

PaulVeenemansPrijsApp/Areas/Admin/Views/Participant/Import.cshtml
@{
    ViewBag.Title = "Deelnemers importeren";
}

<h2>@ViewBag.Title</h2>

<p>Volgorde van de velden moet zijn:</p>
<ol style="list-style-type: upper-alpha;">
    <li>Teamnummer</li>
    <li>Chipnummer</li>
    <li>Racecode groot</li>
    <li>Racecode klein</li>
    <li>Teamcode</li>
    <li>Naam deelnemer</li>
    <li>Code roeien ("1x", "2x" of "2-")</li>
    <li>Racegroep (=wedstrijd, indien weggelaten wordt de eerste genomen)</li>
</ol>
<p>
    Je moet echt <em>precies</em> deze volgorde aanhouden! De eerste regel wordt<br/>
    <span style="text-decoration: underline;">altijd</span> overgeslagen. (Daar kun je dus kolomkoppen plaatsen.)
</p>

@using (Html.BeginForm("Import", "Participant", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div>
        <div class="editor-label">Excel-bestand</div>
        <div class="editor-field">
            <input type="file" name="file" id="file"/>
        </div>
    </div>
    <p>
        <input type="submit" value="Importeren"/> |
        @Html.ActionLink("Back to List", "Index")
    </p>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <hr/>
    <h4>Aanpassen vanuit Excel</h4>
    <em>
        Het gedownloade document kun je na aanpassing weer uploaden via het formulier hierboven.<br/>
        Let op: gebruik deze methode <span style="text-decoration: underline;">niet</span> als er al uitslagen in het systeem zitten.
    </em>
    <p>
        @Html.ActionLink("Laatste voorgaande deelnemersimport downloaden", "Download")
    </p>
}

PaulVeenemansPrijsApp/Areas/Admin/Views/Participant/_FilterPartial.cshtml
<div class="filter">
    @using (Html.BeginForm("Index", "Participant", FormMethod.Get))
    {
        if (!string.IsNullOrEmpty(ViewBag.sort.Column))
        {
            <input type="hidden" name="Column" value="@ViewBag.sort.Column"/>
            <input type="hidden" name="Direction" value="@ViewBag.sort.Direction"/>
        }
        <input id="filter" name="filter" value="@ViewBag.filter" />
        <input id="submit" type="submit" value="Filteren" />
        if (!string.IsNullOrEmpty(ViewBag.filter))
        {
            @Html.MtkActionLink("Filter uit", "Index", new {filter = ""})
        }
    }
</div>